image: node:latest

stages:
  - build
  - test
  - lint

build-job:
  stage: build
  script:
    - npm install
    
test-job:
  stage: test
  script:
    - npm install
    - npm test

lint-job:
  stage: lint
  script:
    - npm install
    - npm run lint
