image: node:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - lint

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - npm install
    
test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 5 seconds."
    - sleep 5
    - echo "Code coverage is 90%"

lint-job:   # This job also runs in the test stage.
  stage: lint    # It can run at the same time as unit-test-job (in parallel).
  script:
    - npm install eslint
    - npm run lint
